name: github release
on:
  workflow_call:
permissions:
  contents: write
  pages: write
  id-token: write
  actions: read
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CONVEYOR_AGREE_TO_LICENSE: 1
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm i

      - name: Install Conveyor
        run: npm install -g @hydraulic/conveyor

      - run: conveyor keys generate --no-passphrase

      - name: Build executable
        run: conveyor make copied-site
        env:
          OAUTH_TOKEN: ${{ github.token }}
