name: build
on:
  workflow_call:
    inputs:
      build-artifact-id:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Get current app version
        id: get-version
        run: echo "version=$(node -p require('./package.json').version)" >> $GITHUB_OUTPUT

      - name: Download build artifact
        id: download-artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.build-artifact-id }}

      - name: Release ${{ steps.get-version.outputs.version }}
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          name: ${{ steps.get-version.outputs.version }}
          tag_name: ${{ steps.get-version.outputs.version }}
          files: My app.app
